export const BUTTON_TYPES = {
  SMALL: "SMALL",
  BIG: "BIG",
  BIG_ORANGE: "BIG_ORANGE",
};

export const TEXT_ABOUT_TYPES = {
  SMILE: "SMILE",
  DIALOGUE: "DIALOGUE",
  LIKE: "LIKE",
  CHECK: "CHECK",
};

export const HOW_IT_WORKS_CARDS = {
  PLUS: "PLUS",
  CHART: "CHART",
  PRAXIS: "PRAXIS",
};

export const TEAM = {
  ANDROID_EVGENIY: "ANDROID_EVGENIY",
  PROJECT_MANAGER_MARIA: "PROJECT_MANAGER_MARIA",
  PROJECT_MANAGER_VIKTORIA: "PROJECT_MANAGER_VIKTORIA",
  PSIHOLOG_IRINA: "PSIHOLOG_IRINA",
  QA_MARINA: "QA_MARINA",
  QA_MARIA: "QA_MARIA",
  FRONTEND_ANNA: "FRONTEND_ANNA",
  QA_IRINA: "QA_IRINA",
  UXUI_ANDREY: "UXUI_ANDREY",
  AQA_NATALIA: "AQA_NATALIA",
  BA_ELENA: "BA_ELENA",
  BACKEND_ARTEM: "BACKEND_ARTEM",
  DA_ALENA: "DA_ALENA:",
  BACKEND_SERGEY: "BACKEND_SERGEY",
  ILLUSTRATOR_IRINA: "ILLUSTRATOR_IRINA",
  FULLSTACK_ANONIM: "FULLSTACK_ANONIM",
};
